(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
  const colors={line:'#314659',text:'#edf4fb',muted:'#94a7b8',a:'#d3a95e',b:'#72b7d3',c:'#79c69c',d:'#d88778'};
  const NS='http://www.w3.org/2000/svg';
  const E=(tag,a={})=>{const x=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>x.setAttribute(k,v));return x};
  const clear=s=>{while(s.firstChild)s.removeChild(s.firstChild)};
  const line=(s,x1,y1,x2,y2,a={})=>s.appendChild(E('line',{x1,y1,x2,y2,stroke:colors.line,'stroke-width':1,...a}));
  const text=(s,x,y,z,a={})=>{const e=E('text',{x,y,fill:colors.text,'font-size':11,...a});e.textContent=z;s.appendChild(e)};
  const path=(s,d,a={})=>s.appendChild(E('path',{d,fill:'none',stroke:colors.text,'stroke-width':2,...a}));
  const f=(x,n=3)=>Number.isFinite(x)?x.toFixed(n):'—';
  $$('.tab').forEach(btn=>btn.addEventListener('click',()=>{$$('.tab').forEach(b=>b.classList.toggle('active',b===btn));$$('.pane').forEach(p=>p.classList.toggle('active',p.id==='pane-'+btn.dataset.tab));}));
  function pyramid(){const H=146.6,t=+$('#pTau').value/100,u=1-t,z=H*u,removedMass=t**3,removedEnergy=clamp(1-6*u*u+8*u**3-3*u**4,0,1),floor=43,top=48.8,superTop=64.5,rho=+$('#pRho').value;let eta,state,detail;if(z>=top){eta=1;state=z>=superTop?'Cavidad cerrada y encapsulada':'Cavidad cerrada; superestructura expuesta';detail='El espacio negativo sigue topológicamente diferenciado del exterior.'}else if(z>floor){eta=(z-floor)/(top-floor);state='Cavidad abierta';detail='Al desaparecer parte del techo, el vacío se conecta con el espacio constructivo exterior.'}else{eta=0;state='Identidad de cámara extinguida';detail='El volumen ya no está delimitado como objeto arquitectónico negativo.'}const neg=-10.5*5.2*5.8*rho*eta;$('#pTauV').textContent=(t*100).toFixed(1)+' %';$('#pRhoV').textContent=f(rho,2)+' t/m³';$('#pZ').textContent=f(z,1)+' m';$('#pM').textContent=(removedMass*100).toFixed(1)+' %';$('#pU').textContent=(removedEnergy*100).toFixed(1)+' %';$('#pN').textContent=f(neg,0)+' t-eq';$('#pState').textContent=state;$('#pDetail').textContent=detail;const s=$('#pyrSvg');clear(s);const bx=260,by=315,ay=25,hw=205,y=by-(z/H)*(by-ay),w=hw*(1-z/H);s.appendChild(E('polygon',{points:'260,25 55,315 465,315',fill:'none',stroke:colors.text,'stroke-width':2}));s.appendChild(E('polygon',{points:`55,315 465,315 ${bx+w},${y} ${bx-w},${y}`,fill:colors.a,'fill-opacity':.18}));line(s,bx-w,y,bx+w,y,{stroke:colors.b,'stroke-width':2,'stroke-dasharray':'6 5'});const Y=zz=>by-(zz/H)*(by-ay),yt=Y(top),yf=Y(floor);s.appendChild(E('rect',{x:235,y:yt,width:50,height:Math.max(4,yf-yt),fill:colors.c,'fill-opacity':eta?.28:.06,stroke:colors.c,'stroke-width':2,'stroke-dasharray':eta<1?'5 4':'0'}));line(s,220,Y(superTop),300,Y(superTop),{stroke:colors.d,'stroke-width':3});text(s,306,Y(superTop)+4,'~64.5 m',{fill:colors.muted});text(s,306,Y(top)+4,'~48.8 m',{fill:colors.muted});text(s,306,Y(floor)+4,'~43 m*',{fill:colors.muted});text(s,18,22,'frente geométrico inverso',{fill:colors.muted});}
  function mv(v,w){if(v<=-w)return 0;if(v>=w)return 1;const s=(v+w)/(2*w);return 3*s*s-2*s*s*s}
  function ehCurve(w){const out=[],v0=6,v1=-6,n=700;let r=2,v=v0;out.push([v,r]);const F=(x,y)=>y<=1e-6?.5:.5*(1-2*mv(x,w)/y);for(let i=1;i<n;i++){const vn=v0+(v1-v0)*i/(n-1),h=vn-v;if(r<=1e-6){r=0;v=vn;out.push([v,r]);continue}const k1=F(v,r),k2=F(v+h/2,r+h*k1/2),k3=F(v+h/2,r+h*k2/2),k4=F(v+h,r+h*k3);r=Math.max(0,r+h*(k1+2*k2+2*k3+k4)/6);v=vn;out.push([v,r])}return out.reverse()}
  function interp(a,x){for(let i=1;i<a.length;i++)if(a[i][0]>=x){const p=a[i-1],n=a[i],t=(x-p[0])/(n[0]-p[0]);return p[1]+t*(n[1]-p[1])}return x<a[0][0]?a[0][1]:a[a.length-1][1]}
  function vaidya(){const v=+$('#vT').value,w=+$('#vW').value,r=+$('#vR').value,m=mv(v,w),ah=2*m,th=(r-2*m)/(r*r),curve=ehCurve(w),eh=interp(curve,v);$('#vTV').textContent=f(v,2);$('#vWV').textContent=f(w,2);$('#vRV').textContent=f(r,2);$('#vM').textContent=f(m);$('#vAH').textContent=f(ah);$('#vEH').textContent=f(eh);$('#vTh').textContent=f(th);$('#vState').textContent=ah>0&&r<ah?'θ+ < 0: el punto de prueba está dentro de la región atrapada del modelo':th>0?'θ+ > 0: expansión saliente':'θ+ ≈ 0: frontera aparente';const s=$('#vSvg');clear(s);const L=45,R=535,T=25,B=310,X=x=>L+(x+6)/12*(R-L),Y=y=>B-clamp(y,0,3.2)/3.2*(B-T);line(s,L,B,R,B);line(s,L,T,L,B);let a='',e='';curve.forEach((p,i)=>{a+=(i?' L':'M')+X(p[0])+' '+Y(2*mv(p[0],w));e+=(i?' L':'M')+X(p[0])+' '+Y(p[1])});path(s,a,{stroke:colors.b});path(s,e,{stroke:colors.a});line(s,X(v),T,X(v),B,{stroke:colors.c,'stroke-dasharray':'5 4'});s.appendChild(E('circle',{cx:X(v),cy:Y(r),r:5,fill:ah>0&&r<ah?colors.d:colors.c}));text(s,360,45,'AH: r=2m(v)',{fill:colors.b});text(s,360,62,'EH: generador global',{fill:colors.a});text(s,280,340,'v/M',{'text-anchor':'middle',fill:colors.muted});}
  function KR(r,a,b){const D=r*r-2*r+a*a;return (r*r+a*a-a*b)**2-D*(b-a)**2}function rph(a){return a<1e-8?3:2*(1+Math.cos((2/3)*Math.acos(-a)))}function bc(a){if(a<1e-8)return 3*Math.sqrt(3);const r=rph(a);return -(r**3-3*r*r+a*a*r+a*a)/(a*(r-1))}function roots(a,b,r0,r1){const o=[],n=900;let x0=r0,y0=KR(x0,a,b);for(let i=1;i<=n;i++){const x=r0+(r1-r0)*i/n,y=KR(x,a,b);if(y*y0<0){let lo=x0,hi=x,fl=y0;for(let j=0;j<38;j++){const m=(lo+hi)/2,fm=KR(m,a,b);if(fl*fm<=0)hi=m;else{lo=m;fl=fm}}const z=(lo+hi)/2;if(!o.some(k=>Math.abs(k-z)<1e-3))o.push(z)}x0=x;y0=y}return o}function comps(a,b,r0,r1){let n=0,on=false;for(let i=0;i<=600;i++){const r=r0+(r1-r0)*i/600,ok=KR(r,a,b)>=0;if(ok&&!on){n++;on=true}if(!ok)on=false}return n}
  function kerr(){const a=+$('#kA').value,b=+$('#kB').value,h=1+Math.sqrt(1-a*a),ph=rph(a),crit=bc(a),r0=h+.003,r1=8,rr=roots(a,b,r0,r1),beta=comps(a,b,r0,r1);$('#kAV').textContent=f(a);$('#kBV').textContent=f(b);$('#kHp').textContent=f(h);$('#kPh').textContent=f(ph);$('#kBc').textContent=f(crit);$('#kBeta').textContent=beta;$('#kRoots').textContent=rr.length?'Raíces R=0: '+rr.map(x=>f(x)+'M').join(', '):'Sin turning points externos detectados';$('#kState').textContent=Math.abs(b-crit)<.015?'Separatriz: R≈0 y ∂R/∂r≈0 en el light ring':beta>1?'Una banda radial prohibida separa el dominio R≥0':'El dominio radial permitido permanece conectado';const s=$('#kSvg');clear(s);const L=45,R=535,T=28,B=310,X=x=>L+(x-r0)/(r1-r0)*(R-L),mid=170;let mx=1e-9,pts=[];for(let i=0;i<=600;i++){const r=r0+(r1-r0)*i/600,v=KR(r,a,b);pts.push([r,v]);mx=Math.max(mx,Math.abs(v))}line(s,L,mid,R,mid,{'stroke-dasharray':'4 4'});let d='';pts.forEach((p,i)=>d+=(i?' L':'M')+X(p[0])+' '+(mid-clamp(p[1]/mx,-1,1)*115));path(s,d,{stroke:colors.b});rr.forEach(x=>line(s,X(x),T,X(x),B,{stroke:colors.a,'stroke-dasharray':'4 4'}));line(s,X(ph),T,X(ph),B,{stroke:colors.c,'stroke-width':2});text(s,X(ph)+4,48,'rph',{fill:colors.c});text(s,280,340,'r/M',{'text-anchor':'middle',fill:colors.muted});}
  ['#pTau','#pRho','#vT','#vW','#vR','#kA','#kB'].forEach(s=>$(s).addEventListener('input',()=>{pyramid();vaidya();kerr()}));pyramid();vaidya();kerr();
})();
